### ISSUE TITLE
Adjust some styling to documentation pages

### ISSUE THREAD

**Issue by abrahamnavas** [Stratio/egeo-web#84]
It is necessary to make the following style adjustments:

Component title and main description:
![title_desc](https://cloud.githubusercontent.com/assets/7441029/26390172/af076c9c-405d-11e7-8fb8-5c5d04db334d.png)

```css
Title {
    font-family: BrandonText;
    font-size: 30px;
    color: #405467;
}
```
```css
Underline {
    height: 2px;
    border: solid 2px #3dc9fc;
    margin-top: 8px;
}
````
```css
Body_copy {
    font-family: OpenSans;
    font-size: 16px;
    color: #555555;
    margin-top: 25px;
}
```

Section title and descriptional copy:
![section_copy](https://cloud.githubusercontent.com/assets/7441029/26390702/008cd0a0-4060-11e7-8ddc-1d7e2c7f7ceb.png)

```css
Section_title {
    font-family: OpenSans;
    font-size: 26px;
    color: #405467;
}
```
```css
Descirptional_copy {
    font-family: OpenSans;
    font-size: 14px;
    color: #555555;
    margin-top: 20px;
}
```
