### ISSUE TITLE
Adjust some styles in themes' section

### ISSUE THREAD

**Issue by abrahamnavas** [Stratio/egeo-web#96]
- [ ] Fix the double-underlined titles. We have to remove the gray one.
- [ ] Adjust the style for the body copies, as follows:
```css
Body_copy {
    font-family: OpenSans;
    font-size: 16px;
    color: #555555;
    margin-top: 25px;
}
```
